public class Program {
    public static void main(String[] args) {
         OffsetHashTable1();
        OffsetHashTable2();
        OffsetHashTable3();

        ListHashTable1();
        ListHashTable2();
        ListHashTable3();
    }


    private static void OffsetHashTable1() {
        HashTable hashTable = new OffsetHashTable(13);
        System.out.println("Offset_hash_1");
        hashTable.insert( 70);
        hashTable.print();
        System.out.println();
        hashTable.insert( 40);
        hashTable.print();
        System.out.println();
        hashTable.insert( 78);
        hashTable.print();
        System.out.println();
        hashTable.insert( 43);
        hashTable.print();
        System.out.println();
        hashTable.insert( 16);
        hashTable.print();
        System.out.println();
        hashTable.insert( 26);
        hashTable.print();
        System.out.println();
        hashTable.insert( 5);
        hashTable.print();
        System.out.println();
        hashTable.insert( 11);
        hashTable.print();
        System.out.println();
        hashTable.insert( 14);
        hashTable.print();
        System.out.println();
        hashTable.insert( 54);
        hashTable.print();
        System.out.println();
        hashTable.insert( 49);
        hashTable.print();
        System.out.println();
        hashTable.insert( 89);
        hashTable.print();
    }

    private static void OffsetHashTable2() {
        HashTable hashTable = new OffsetHashTable(19);
        System.out.println(" Offset_hash_2");
        hashTable.insert( 40);
        hashTable.print();
        System.out.println();
        hashTable.insert( 24);
        hashTable.print();
        System.out.println();
        hashTable.insert( 73);
        hashTable.print();
        System.out.println();
        hashTable.insert( 75);
        hashTable.print();
        System.out.println();
        hashTable.insert( 60);
        hashTable.print();
        System.out.println();
        hashTable.insert( 40);
        hashTable.print();
        System.out.println();
        hashTable.insert( 84);
        hashTable.print();
        System.out.println();
        hashTable.insert(23);
        hashTable.print();
        System.out.println();
        hashTable.insert(67);
        hashTable.print();
        System.out.println();
        hashTable.insert(91);
        hashTable.print();
        System.out.println();
        hashTable.insert(6);
        hashTable.print();
        System.out.println();
        hashTable.insert(54);
        hashTable.print();
        System.out.println();
        hashTable.insert(32);
        hashTable.print();
        System.out.println();
        hashTable.insert(78);
        hashTable.print();
        System.out.println();
        hashTable.insert(59);
        hashTable.print();
        System.out.println();
        hashTable.remove(60);
        hashTable.print();
        System.out.println();
        hashTable.remove(91);
        hashTable.print();
        System.out.println();
        hashTable.remove(6);
        hashTable.print();
        System.out.println();
        hashTable.remove(32);
        hashTable.print();
        System.out.println();
        hashTable.remove(84);
        hashTable.print();
        System.out.println();
    }

    private static void OffsetHashTable3() {
        HashTable hashTable = new OffsetHashTable(19);
        System.out.println(" Offset_hash_3");
        hashTable.insert( 35);
        hashTable.print();
        System.out.println();
        hashTable.insert( 19);
        hashTable.print();
        System.out.println();
        hashTable.insert( 84);
        hashTable.print();
        System.out.println();
        hashTable.insert( 61);
        hashTable.print();
        System.out.println();
        hashTable.insert( 56);
        hashTable.print();
        System.out.println();
        hashTable.insert( 77);
        hashTable.print();
        System.out.println();
        hashTable.insert( 16);
        hashTable.print();
        System.out.println();
        hashTable.insert( 4);
        hashTable.print();
        System.out.println();
        hashTable.insert( 8);
        hashTable.print();
        System.out.println();
        hashTable.insert( 33);
        hashTable.print();
        System.out.println();
        hashTable.insert( 28);
        hashTable.print();
        System.out.println();
        hashTable.insert( 99);
        hashTable.print();
        System.out.println();
        hashTable.remove( 99);
        hashTable.print();
        System.out.println();
        hashTable.remove( 19);
        hashTable.print();
        System.out.println();
        hashTable.remove( 28);
        hashTable.print();
        System.out.println();
        hashTable.insert( 26);
        hashTable.print();
        System.out.println();
        hashTable.insert( 38);
        hashTable.print();
        System.out.println();
        hashTable.insert( 87);
        hashTable.print();
        System.out.println();
        hashTable.remove( 26);
        hashTable.print();
        System.out.println();
        hashTable.remove( 77);
        hashTable.print();
        System.out.println();
        hashTable.insert( 76);
        hashTable.print();
        System.out.println();
        hashTable.insert( 44);
        hashTable.print();
        System.out.println();
        hashTable.insert( 44);
        hashTable.print();
        System.out.println();
        hashTable.remove( 84);
        hashTable.print();
        System.out.println();
        hashTable.remove( 35);
        hashTable.print();
        System.out.println();
        hashTable.remove( 61);
        hashTable.print();
        System.out.println();
        hashTable.remove( 33);
        hashTable.print();
        System.out.println();
        hashTable.remove( 8);
        hashTable.print();
        System.out.println();
    }
///////////////////////////////////////////////////////////////
    private static void ListHashTable1() {
        HashTable hashTable = new ListHashTable(13);
        System.out.println(" List_hash_1");
        hashTable.insert(37);
        hashTable.print();
        hashTable.insert(43);
        hashTable.print();
        hashTable.insert(98);
        hashTable.print();
        hashTable.insert(93);
        hashTable.print();
        hashTable.insert(48);
        hashTable.print();
        hashTable.insert(33);
        hashTable.print();
        hashTable.insert(66);
        hashTable.print();
        hashTable.insert(37);
        hashTable.print();
        hashTable.insert(96);
        hashTable.print();
        hashTable.insert(67);
        hashTable.print();
        hashTable.insert(33);
        hashTable.print();
        hashTable.insert(74);
        hashTable.print();
    }
    //////
    private static void ListHashTable2() {
        HashTable hashTable = new ListHashTable(19);
        System.out.println(" List_hash_2");
        hashTable.insert( 39);
        hashTable.print();
        hashTable.insert( 60);
        hashTable.print();
        hashTable.insert( 75);
        hashTable.print();
        hashTable.insert( 53);
        hashTable.print();
        hashTable.insert( 62);
        hashTable.print();
        hashTable.insert( 2);
        hashTable.print();
        hashTable.insert( 72);
        hashTable.print();
        hashTable.insert( 85);
        hashTable.print();
        hashTable.insert( 53);
        hashTable.print();
        hashTable.insert( 42);
        hashTable.print();
        hashTable.insert( 47);
        hashTable.print();
        hashTable.insert( 96);
        hashTable.print();
        hashTable.insert( 95);
        hashTable.print();
        hashTable.insert( 39);
        hashTable.print();
        hashTable.insert( 93);
        hashTable.print();
        hashTable.remove( 85);
        hashTable.print();
        hashTable.remove( 53);
        hashTable.print();
        hashTable.remove( 95);
        hashTable.print();
        hashTable.remove( 93);
        hashTable.print();
        hashTable.remove( 75);
        hashTable.print();
    }
//////
    private static void ListHashTable3() {
        HashTable hashTable = new ListHashTable(19);
        System.out.println(" List_hash_3");
        hashTable.insert( 4);
        hashTable.print();
        hashTable.insert( 39);
        hashTable.print();
        hashTable.insert( 93);
        hashTable.print();
        hashTable.insert( 77);
        hashTable.print();
        hashTable.insert( 51);
        hashTable.print();
        hashTable.insert( 74);
        hashTable.print();
        hashTable.insert( 79);
        hashTable.print();
        hashTable.insert( 77);
        hashTable.print();
        hashTable.insert( 98);
        hashTable.print();
        hashTable.insert( 32);
        hashTable.print();
        hashTable.insert( 67);
        hashTable.print();
        hashTable.insert( 82);
        hashTable.print();
        hashTable.remove( 74);
        hashTable.print();
        hashTable.remove( 4);
        hashTable.print();
        hashTable.remove( 51);
        hashTable.print();
        hashTable.insert( 49);
        hashTable.print();
        hashTable.insert( 72);
        hashTable.print();
        hashTable.insert( 30);
        hashTable.print();
        hashTable.remove( 72);
        hashTable.print();
        hashTable.remove( 32);
        hashTable.print();
        hashTable.insert( 70);
        hashTable.print();
        hashTable.insert( 36);
        hashTable.print();
        hashTable.insert( 30);
        hashTable.print();
        hashTable.remove( 36);
        hashTable.print();
        hashTable.remove( 39);
        hashTable.print();
        hashTable.remove( 93);
        hashTable.print();
        hashTable.remove( 82);
        hashTable.print();
        hashTable.remove( 67);
        hashTable.print();
    }
}
